In [1]:
# Author: Aayush Patel - CS20BTECH11001

In [2]:
import numpy as np
import cvxpy as cp
import pandas as pd

In [3]:
demand = np.array([45, 20, 30, 30, 10])
supply = np.array([40, 50, 45])
n = supply.shape[0]
m = demand.shape[0]
cost = np.array([[8, 6, 10, 9, 8], [9, 12, 13, 7, 5,], [14, 9, 16, 5, 2]])

In [4]:
strategy = cp.Variable(shape=(n,m))
# sum return a dim np array here and demand and suppy are 1 dim
constraints = [cp.sum(strategy, axis=0) >= demand , cp.sum(strategy, axis=1) <= supply, strategy >= 0]
# suppy can be diminised at some remain in factories. Production >= market demand so demand satsfied
objective = cp.Minimize(cp.sum(cp.multiply(strategy, cost)))
optimal_cost = cp.Problem(objective, constraints).solve()

In [7]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print(strategy.value)
print(optimal_cost)
# print(np.array_str(strategy.value, precision=1, suppress_small=True))

[[ 0.000  15.000  25.000  0.000  0.000]
 [ 45.000  0.000  5.000  0.000  0.000]
 [ 0.000  5.000  0.000  30.000  10.000]]
1025.0000000955833
